config/routes.rb
Rails.application.routes.draw do
  resources :movies
  resources :clients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "clients#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :movie, optional: true

  def to_s
    self.name
  end
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :clients

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]
  before_action :set_movies, only: %i[ show new edit create destroy update]
  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :age, :movie_id)
    end

    def set_movies
      @movies = Movie.all.pluck :name, :id
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]

  # GET /movies or /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end    

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
  <tr>
    <th scope="row"><%= client.id %></th>
    <td><%= client.name %></td>
    <td><%= client.age %></td>
    <% if client.movie.present? %>
      <td><%= client.movie.name %></td>
    <% else %>
      <td class="text-danger">Client has no movies</td>
    <% end %>        
    <td><%= link_to "Show this client", client, class: "btn btn-outline-success btn-sm" %></td>
    <td><%= link_to "Edit this client", edit_client_path(client), class: "btn btn-outline-warning btn-sm" %></td>
  </tr>
</div>

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.text_field :age %>
  </div>

   

  <div class="btn btn-secondary mt-3">
    <%= form.submit%>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1 class="my-3">Editing client</h1>

<%#= render "form", client: @client %>


<%= form_with(model: @client) do |form| %>
  <% if @client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.text_field :age %>
  </div>

   <div class="my-3">
     <%= form.label :movie_id, style: "display: block" %>
     <%= form.select :movie_id, options_for_select(@movies) %>    
    </div>

  <div class="btn btn-secondary mb-3">
    <%= form.submit%>
  </div>
<% end %>

<div>
  <%= link_to "Show this client", @client, class: "btn btn-success" %>
  <%= link_to "Back to clients", clients_path, class:"btn btn-secondary" %>
</div>

app/views/clients/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <h1>Clients</h1> 

  <div id="clients">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Age</th>
          <th scope="col">Movie</th>
          <th scope="col" colspan="2"></th>
        </tr>
      </thead>
      <tbody>
        <% @clients.each do |client| %>
          <%= render client %>
        <% end %>
      </tbody>
    </table>
  </div>

  <%= link_to "Add new client", new_client_path, class:"btn btn-secondary" %>

</div>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Back to clients", clients_path, class:"btn btn-secondary" %>
</div>

app/views/clients/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="card" style="width: 18rem;">
      <div class="card-header fw-bold">
        Client: <%= @client.name %>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">ID Client: <%= @client.id %></li>
        <li class="list-group-item">Name: <%= @client.name %></li>
        <li class="list-group-item">Age: <%= @client.age %></li>   
        <% if @client.movie.present? %>
          <li class="list-group-item">Movie: <%= @client.movie.name %></li> 
        <% else %>
          <p class="text-danger ms-3">Client has no movies</p>
        <% end %>      
      </ul>            
  </div>

<div>
  <%= link_to "Edit this client", edit_client_path(@client), class: "btn btn-warning m-3" %>
  <%= link_to "Back to clients", clients_path, class:"btn btn-secondary" %>
  <%= button_to "Destroy this client", @client, method: :delete, class: "btn btn-danger mx-3" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlockBuster</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <%# <div>
    <%= form.label :client_id, style: "display: block" %>
    <%#= form.select :client_id, options_for_select(@clients) %>
  <%# </div> %>

  <div class="btn btn-secondary mt-3">
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<div class="col-2 py-2" >
<div class="card">
  <% random_number = rand(1..500).to_i %>    
    <img class="card-img-top" src="https://picsum.photos/id/<%= random_number %>/500/280" alt="Imagen aleatoria">  
  <div class="card-body">
    <h5 class="card-title"><%= movie.name %></h5>
        <%= link_to "Show this movie", movie, class: "btn btn-outline-success  btn-sm" %>
     </div>
  </div>
</div>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Show this movie", @movie, class: "btn btn-success" %>
  <%= link_to "Back to movies", movies_path, class:"btn btn-secondary" %>
</div>

app/views/movies/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <h1>Movies</h1>
  <%= link_to "Add new movie", new_movie_path, class:"btn btn-secondary" %>
  
  <div id="movies">

  

    <div class="row">
      <% @movies.each do |movie| %>
      
        <%= render movie %>
      <% end %>
    </div>
  </div>
</div>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Back to movies", movies_path, class:"btn btn-secondary" %>
</div>

app/views/movies/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="card" style="width: 18rem;">
  <% random_number = rand(1..500).to_i %>    
    <img class="card-img-top" src="https://picsum.photos/id/<%= random_number %>/500/280" alt="Imagen aleatoria">  
      <div class="card-header fw-bold">
        <%= @movie.name %>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">ID Movie: <%= @movie.id %></li>
        
      </ul>      
      <strong class="card-text ms-3">Clients: </strong>
          <% if @movie.clients.last.present? %>
              <p class="card-text ms-3">
                  <% @movie.clients.each do |client|%>
                      <%= client.name %> <br>
                  <% end %>                  
           <% else %>
              <p class="text-danger ms-3">No clients yet</p>
          <% end %> 
      </p>
  </div>


<%#= render @movie %>

<div class="my-3">
  <%= link_to "Edit this movie", edit_movie_path(@movie), class: "btn btn-warning me-3" %>
  <%= link_to "Back to movies", movies_path, class:"btn btn-secondary" %>

  <%= button_to "Destroy this movie", @movie, method: :delete, class: "btn btn-danger my-3" %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fs-4">
  <div class="container">
    <h1><%= link_to 'BlockBuster', root_path, class: 'navbar-brand fs-3' %></h1>    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Clients', clients_path, class: 'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to 'Movies', movies_path, class: 'nav-link' %>
        </li>
    </div>
  </div>
</nav>